### PR TITLE
[FIX] : Made it cleaner

### LINKED ISSUE #3: [FIX] : Organize the code and make it cleaner
## What's the issue?

Make the code organized and make it clean

### PR DESCRIPTION
**Pull request by Haarush2006**
## What does this PR do?
Fixes #3 

Made function implementation more cleaner

### CODE REVIEW

File: src/App.jsx [hunk 1]
```diff
@@ -5,21 +5,12 @@ function App() {
...
-  }
-  function Tab4() {
-    SetCrntTab(4)
-    
-  }
+
+  const Tab1 = () => SetCrntTab(1)
+  const Tab2 = () => SetCrntTab(2)
+  const Tab3 = () => SetCrntTab(3)
+  const Tab4 = () => SetCrntTab(4)
```
Comment (Haarush-OS) [inline src/App.jsx:12]: Nice, It looks simpler now

Comment (Haarush2006) [reply src/App.jsx:12]: Thank you!
